name = "api"
main = "src/index.ts"
compatibility_date = "2025-09-23"

[vars]
ALLOWED_ORIGINS = "https://ai-keiba.pages.dev"

[[d1_databases]]
binding = "keiba_db"
database_name = "keiba-db"
database_id = "edad6a04-6653-4a79-818e-0821d353eb2a"
migrations_dir = "migrations"
migrations_table = "d1_migrations"

[observability.logs]
enabled = true